@startuml
class UpperCaseCamelCaseNamingPolicy {
    + <<override>> ConvertName(name:string) : string
}
class CrmJsonOptionsConfigurator {
    + {static} GetConfiguredOptions() : JsonSerializerOptions
    + {static} ConfigureJsonOptions(options:JsonSerializerOptions) : void
}
JsonNamingPolicy <|-- UpperCaseCamelCaseNamingPolicy
@enduml
