// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using POC.Infrastructure;

#nullable disable

namespace POC.Migrations
{
    [DbContext(typeof(OurDbContext))]
    partial class OurDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("POC.Infrastructure.Models.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ScreenProfileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScreenProfileId");

                    b.ToTable("Screens");
                });

            modelBuilder.Entity("POC.Infrastructure.Models.ScreenProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ScreenProfiles");
                });

            modelBuilder.Entity("POC.Infrastructure.Models.Screen", b =>
                {
                    b.HasOne("POC.Infrastructure.Models.ScreenProfile", "ScreenProfile")
                        .WithMany("Screens")
                        .HasForeignKey("ScreenProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScreenProfile");
                });

            modelBuilder.Entity("POC.Infrastructure.Models.ScreenProfile", b =>
                {
                    b.OwnsOne("POC.Infrastructure.Models.ScreenProfileFiltering", "ScreenProfileFiltering", b1 =>
                        {
                            b1.Property<int>("ScreenProfileId")
                                .HasColumnType("integer");

                            b1.Property<List<int>>("EntityIds")
                                .HasColumnType("integer[]");

                            b1.Property<int>("IsPickup")
                                .HasColumnType("integer");

                            b1.Property<int>("IsSale")
                                .HasColumnType("integer");

                            b1.Property<int[]>("OrderStatusses")
                                .HasColumnType("integer[]");

                            b1.HasKey("ScreenProfileId");

                            b1.ToTable("ScreenProfiles");

                            b1.WithOwner()
                                .HasForeignKey("ScreenProfileId");

                            b1.OwnsOne("POC.Infrastructure.Models.OrderTimeRange", "OrderTimeRange", b2 =>
                                {
                                    b2.Property<int>("ScreenProfileFilteringScreenProfileId")
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("EndDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.Property<DateTime>("StartDate")
                                        .HasColumnType("timestamp with time zone");

                                    b2.HasKey("ScreenProfileFilteringScreenProfileId");

                                    b2.ToTable("ScreenProfiles");

                                    b2.WithOwner()
                                        .HasForeignKey("ScreenProfileFilteringScreenProfileId");
                                });

                            b1.Navigation("OrderTimeRange")
                                .IsRequired();
                        });

                    b.Navigation("ScreenProfileFiltering")
                        .IsRequired();
                });

            modelBuilder.Entity("POC.Infrastructure.Models.ScreenProfile", b =>
                {
                    b.Navigation("Screens");
                });
#pragma warning restore 612, 618
        }
    }
}
