@startuml
!include .\\POC\Program.puml
!include .\\POC\Infrastructure\DbContext.puml
!include .\\POC\Api\Conventions\KebabCaseRouteConvention.puml
!include .\\POC\Api\Hubs\GuestHub.puml
!include .\\POC\Api\Hubs\ScreenHub.puml
!include .\\POC\App\Behaviors\LoggingBehavior.puml
!include .\\POC\Contracts\CrmDTOs\OrderDto.puml
!include .\\POC\Contracts\Response\ErrorResponse.puml
!include .\\POC\Contracts\Screen\CreateScreenDto.puml
!include .\\POC\Contracts\Screen\PairScreenDto.puml
!include .\\POC\Contracts\Screen\ScreenDto.puml
!include .\\POC\Contracts\ScreenProfile\CreateScreenProfileDto.puml
!include .\\POC\Contracts\ScreenProfile\ScreenProfileDto.puml
!include .\\POC\Contracts\ScreenProfile\UpdateScreenProfileDto.puml
!include .\\POC\Infrastructure\Adapters\CrmAdapter.puml
!include .\\POC\Infrastructure\Common\CrmJsonOptionsConfigurator.puml
!include .\\POC\Infrastructure\Common\JsonOptionsConfigurator.puml
!include .\\POC\Infrastructure\Extensions\ExceptionExtensions.puml
!include .\\POC\Infrastructure\Extensions\ScreenExtensions.puml
!include .\\POC\Infrastructure\Extensions\ScreenProfileExtensions.puml
!include .\\POC\Infrastructure\Generators\PairCodeGenerator.puml
!include .\\POC\Infrastructure\Models\Screen.puml
!include .\\POC\Infrastructure\Models\ScreenProfile.puml
!include .\\POC\Infrastructure\Repositories\GuestConnectionRepository.puml
!include .\\POC\Infrastructure\Repositories\ScreenProfileRepository.puml
!include .\\POC\Infrastructure\Repositories\ScreenRepository.puml
!include .\\POC\Api\Controllers\ClientControllers\ScreenProfilesController.puml
!include .\\POC\Api\Controllers\ClientControllers\ScreensController.puml
!include .\\POC\Api\Controllers\CrmControllers\OrdersController.puml
!include .\\POC\Api\Controllers\CrmControllers\WebhookController.puml
!include .\\POC\App\Commands\CreateScreenProfile\CreateScreenProfileCommand.puml
!include .\\POC\App\Commands\CreateScreenProfile\CreateScreenProfileCommandHandler.puml
!include .\\POC\App\Commands\DeleteScreenProfile\DeleteScreenProfileCommand.puml
!include .\\POC\App\Commands\DeleteScreenProfile\DeleteScreenProfileCommandHandler.puml
!include .\\POC\App\Commands\OrderAdded\OrderAddedCommand.puml
!include .\\POC\App\Commands\OrderAdded\OrderAddedCommandHandler.puml
!include .\\POC\App\Commands\OrderDeleted\OrderDeletedCommand.puml
!include .\\POC\App\Commands\OrderDeleted\OrderDeletedCommandHandler.puml
!include .\\POC\App\Commands\OrderUpdated\OrderUpdatedCommand.puml
!include .\\POC\App\Commands\OrderUpdated\OrderUpdatedCommandHandler.puml
!include .\\POC\App\Commands\PairScreen\PairScreenCommand.puml
!include .\\POC\App\Commands\PairScreen\PairScreenCommandHandler.puml
!include .\\POC\App\Commands\RemoveScreen\RemoveScreenCommand.puml
!include .\\POC\App\Commands\RemoveScreen\RemoveScreenCommandHandler.puml
!include .\\POC\App\Commands\UpdateScreenProfile\UpdateScreenProfileCommand.puml
!include .\\POC\App\Commands\UpdateScreenProfile\UpdateScreenProfileCommandHandler.puml
!include .\\POC\App\Queries\GetAllOrders\GetAllOrdersQuery.puml
!include .\\POC\App\Queries\GetAllOrders\GetAllOrdersQueryHandler.puml
!include .\\POC\App\Queries\GetAllScreenProfiles\GetAllScreenProfilesQuery.puml
!include .\\POC\App\Queries\GetAllScreenProfiles\GetAllScreenProfilesQueryHandler.puml
!include .\\POC\App\Queries\GetAllScreens\GetAllScreensQuery.puml
!include .\\POC\App\Queries\GetAllScreens\GetAllScreensQueryHandler.puml
!include .\\POC\App\Queries\GetOrder\GetOrderByIdQuery.puml
!include .\\POC\App\Queries\GetOrder\GetOrderByIdQueryHandler.puml
!include .\\POC\App\Queries\GetScreen\GetScreenQuery.puml
!include .\\POC\App\Queries\GetScreen\GetScreenQueryHandler.puml
!include .\\POC\App\Queries\GetScreenProfile\GetScreenProfileQuery.puml
!include .\\POC\App\Queries\GetScreenProfile\GetScreenProfileQueryHandler.puml
!include .\\POC\Infrastructure\Common\Exceptions\IncorrectPairingCodeException.puml
!include .\\POC\Infrastructure\Common\Exceptions\PairingCodeDoesNotExistException.puml
!include .\\POC\Infrastructure\Common\Exceptions\ScreenAlreadyPairedException.puml
!include .\\POC\Infrastructure\Common\Exceptions\ScreenNotFoundException.puml
!include .\\POC\Infrastructure\Common\Exceptions\ScreenProfileNotFoundException.puml
!include .\\POC\Infrastructure\Common\Validators\CreateScreenProfileDtoValidator.puml
!include .\\POC\Infrastructure\Common\Validators\PairScreenDtoValidator.puml
!include .\\POC\Infrastructure\Common\Validators\UpdateScreenProfileDtoValidator.puml
!include .\\POC\obj\Debug\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\POC\obj\Debug\net8.0\POC.AssemblyInfo.puml
!include .\\POC\obj\Debug\net8.0\POC.GlobalUsings.g.puml
!include .\\POC\obj\Debug\net8.0\POC.MvcApplicationPartsAssemblyInfo.puml
!include .\\POC\obj\Release\net8.0\.NETCoreApp,Version=v8.0.AssemblyAttributes.puml
!include .\\POC\obj\Release\net8.0\POC.AssemblyInfo.puml
!include .\\POC\obj\Release\net8.0\POC.GlobalUsings.g.puml
@enduml
