@startuml
class GetScreenProfileQueryHandler {
    + <<async>> Handle(request:GetScreenProfileQuery, cancellationToken:CancellationToken) : Task<ScreenProfileDto>
}
"IRequestHandler`2" "<GetScreenProfileQuery,ScreenProfileDto>" <|-- GetScreenProfileQueryHandler
@enduml
