@startuml
class GuestHub {
    - {static} <<readonly>> MsgScreenAdded : string = "screenAdded"
    - {static} <<readonly>> MsgPairCode : string = "pairCode"
    - <<readonly>> _pairCodeGenerator : PairCodeGenerator
    + <<override>> <<async>> OnConnectedAsync() : Task
    + <<async>> OnSuccessfulPairing(pairingCode:string) : Task
    + <<override>> <<async>> OnDisconnectedAsync(exception:Exception?) : Task
    - <<async>> SendMessageToClient(pairCode:string, method:string, message:T) : Task
    + <<async>> SendMessageAddScreen(pairCode:string, screenDto:ScreenDto) : Task
    - <<async>> SendMessagePairCode(pairCode:string) : Task
}
Hub <|-- GuestHub
@enduml
